// DO NOT EDIT: This file is managed by Illuminated Cloud. Any external changes will be discarded.

declare interface FlowRecord extends SObject 
{
    ActiveVersion?: FlowRecordVersion;
    ActiveVersionId?: string;
    ApiName?: string;
    ApiVersion?: number;
    AssociatedRecord?: Campaign;
    AssociatedRecordId?: string;
    Builder?: string;
    CapacityCategory?: string;
    ContextRecord?: FlowExecutionErrorEvent;
    CreatedBy?: User;
    CreatedById?: string;
    CreatedDate?: string;
    Description?: string;
    ErrorCode?: string;
    ErrorDetails?: string;
    FlowCategory?: string;
    FlowDefinition?: string;
    FlowLabel?: string;
    FlowRecord?: FlowRecordVersionChangeEvent;
    FlowRecordVersionOccurrences?: FlowRecordVersionOccurrence[];
    FlowRecordVersions?: FlowRecordVersion[];
    FlowSubcategory?: string;
    FlowType?: string;
    InstalledPackageName?: string;
    IsCitizenEnabled?: boolean;
    IsDeleted?: boolean;
    IsOverridable?: boolean;
    IsPaused?: boolean;
    IsTemplate?: boolean;
    LastModifiedBy?: User;
    LastModifiedById?: string;
    LastModifiedDate?: string;
    LastReferencedDate?: string;
    LastViewedDate?: string;
    ManageableState?: string;
    Name?: string;
    NamespacePrefix?: string;
    OverriddenBy?: FlowRecord;
    OverriddenById?: string;
    OverriddenFlow?: FlowRecord;
    OverriddenFlowId?: string;
    Owner?: SObject;
    OwnerId?: string;
    ProgressStatus?: string;
    RelatedRecord?: FlowRecordRelation;
    ScheduledStartDate?: string;
    Shares?: FlowRecordShare[];
    SourceTemplate?: FlowRecord;
    SourceTemplateId?: string;
    StartSource?: string;
    SystemModstamp?: string;
    TargetObject?: PendingServiceRoutingInteractionInfo;
    TriggerObjectOrEventLabel?: string;
    Type?: string;
}